#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2009-2018 the sqlparse authors and contributors
# <see AUTHORS file>
#
# This example is part of python-sqlparse and is released under
# the BSD License: https://opensource.org/licenses/BSD-3-Clause
#
# This example illustrates how to extract table names from nested
# SELECT statements.
#
# See:
# https://groups.google.com/forum/#!forum/sqlparse/browse_thread/thread/b0bd9a022e9d4895

import sqlparse
from sqlparse.sql import IdentifierList, Identifier
from sqlparse.tokens import Keyword, DML


def is_subselect(parsed):
    if not parsed.is_group:
        return False
    for item in parsed.tokens:
        if item.ttype is DML and item.value.upper() == 'SELECT':
            return True
    return False


def extract_from_part(parsed):
    from_seen = False
    for item in parsed.tokens:
        if from_seen:
            if is_subselect(item):
                for x in extract_from_part(item):
                    yield x
            elif item.ttype is Keyword:
                raise StopIteration
            else:
                yield item
        elif item.ttype is Keyword and item.value.upper() == 'FROM':
            from_seen = True



def loopallnode(p):
    for i in range(0,len(p.tokens)):
        if isinstance(p.tokens[i], Identifier) or isinstance(p.tokens[i], IdentifierList):
#          print p.tokens[i].value,p.tokens[i-2].value.upper()
          if i>=2 :
            m = p.tokens[i-2].value.upper()
            if  m == 'FROM' or m == 'INTO' or m == 'UPDATE' or m == 'TABLE' or m == 'DESC' or m == 'DESCRIBE' or m =='VIEW':
                 if hasattr(p.tokens[i],'tokens') :
                       for j in range (0, len(p.tokens[i].tokens)):
                          if isinstance(p.tokens[i].tokens[j], Identifier) :
                             print p.tokens[i].tokens[j].value
#                             p.tokens[i].tokens[j].tokens[0].value = "ooo"
                          else:
                             print p.tokens[i].value
#                             p.tokens[i].tokens[0].value="kkk1"

#
                       pass
        if  hasattr(p.tokens[i],'tokens') :
           loopallnode(p.tokens[i])
        else:
           pass



def extract_tables(sql):
    global p1
    stream = extract_from_part(sqlparse.parse(sql)[0])
    p1 = sqlparse.parse(sql)[0]
    print p1._pprint_tree()
    loopallnode(p1)
#    print str(p1)
    return list(extract_table_identifiers(stream))



if __name__ == '__main__':
    sql = """
    select K.a,K.b from (select H.b from (select G.c from (select F.d from
    (select E.e from A, B, C, D, E), F), G), H), I, J, K order by 1,2;
    """

    tables = ', '.join(extract_tables(sql))
    print('Tables: {0}'.format(tables))
